### PR TITLE
Update base.html

### LINKED ISSUE #78: Navbar not styled properly in phone view
**Describe the bug**
There's a vertical gap in the heading due to the drop-down hamburger button as they don't fit together on the screen.

**To Reproduce**
1. Switch to phone view
2. See error

**Expected behavior**
There should be proper padding and margin in image heading and hamburger menu when switched to the phone view.

**Screenshots**
responsiveness

### PR DESCRIPTION
**Pull request by Kartik-3004**
resolved navbar mobile view issue #78

### Description
There was a vertical gap between heading and navbar. resolved by changing margins

Fixes #78 

### Type of Change:
Added internal css style and some class names to resolve the issue

### CODE REVIEW

**Comment by Tanuj22** [comment]
Also, attach a screenshot .

**Comment by Kartik-3004** [comment]
IMG_4638
Ipad view
IMG_4639
width - 700px
IMG_4640
width - 600px
IMG_4642
width - 500px
IMG_4641
width - 411px
IMG_4643
width - 360 px

**Comment by Kartik-3004** [comment]
@Tanuj22 I am not able to understand how to use interactive rebase and what is it used for? Can you please explain

**Comment by Tanuj22** [comment]
@Kartik-3004 Basically it is used to make changes in commits that you have pushed. You can `squash, reword, pick` a commit among other things. This this case you just need to reword the commit to have a better commit message

**Comment by Kartik-3004** [comment]
@Tanuj22 I changed the commit message. You can merge!

**Comment by Tanuj22** [comment]
Its still not chnaged

**Pull request closed without merging**
